; HEADER_BLOCK_START
; generated by BambuStudio 1.9.0
; printer_model = Bambu Lab X1 Carbon
; filament_settings_id = "Bambu PLA Basic"
; total estimated time: 45m 12s
; total filament weight [g]: 22.4
; HEADER_BLOCK_END
G28
