; generated by PrusaSlicer 2.7.4 on 2026-01-15 at 12:34:56
; printer_model = MK4
; filament_type = PLA
G28 ; home
M104 S210
; filament used [g] = 47.2
; estimated printing time (normal mode) = 1h 23m 45s
M84
