import { render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import JSZip from 'jszip';
import FileDropZone from './FileDropZone';

const prusaSample = `; generated by PrusaSlicer 2.7.4
; printer_model = MK4
; filament_type = PLA
; filament used [g] = 47.2
; estimated printing time (normal mode) = 1h 23m 45s
`;

test('reads dropped file, parses, and calls onImport', async () => {
  const onImport = jest.fn();
  const onError = jest.fn();
  render(<FileDropZone onImport={onImport} onError={onError} />);

  const file = new File([prusaSample], 'sample.gcode', { type: 'text/plain' });
  const input = screen.getByLabelText(/g-code file input/i) as HTMLInputElement;
  await userEvent.upload(input, file);

  await waitFor(() => expect(onImport).toHaveBeenCalledTimes(1));
  expect(onImport.mock.calls[0][0].flavor).toBe('PrusaSlicer');
});

test('calls onError for unsupported file', async () => {
  const onImport = jest.fn();
  const onError = jest.fn();
  render(<FileDropZone onImport={onImport} onError={onError} />);

  const file = new File(['not a gcode'], 'sample.gcode', { type: 'text/plain' });
  const input = screen.getByLabelText(/g-code file input/i) as HTMLInputElement;
  await userEvent.upload(input, file);

  await waitFor(() => expect(onError).toHaveBeenCalledTimes(1));
  expect(onError.mock.calls[0][0].kind).toBe('unsupported_slicer');
});

test('shows imported summary when importedSource provided', () => {
  render(
    <FileDropZone
      onImport={() => {}}
      onError={() => {}}
      imported={{ source: 'PrusaSlicer', printer: 'MK4', filamentType: 'PLA', grams: 47.2, hoursLabel: '1h 23m' }}
      onClearImport={() => {}}
    />,
  );
  expect(screen.getByText(/PrusaSlicer/)).toBeInTheDocument();
  expect(screen.getByText(/MK4/)).toBeInTheDocument();
});

test('parses .3mf file and calls onImport', async () => {
  const onImport = jest.fn();
  const onError = jest.fn();
  render(<FileDropZone onImport={onImport} onError={onError} />);

  const zip = new JSZip();
  zip.file('Metadata/slice_info.config', `<?xml version="1.0" encoding="UTF-8"?>
<config>
  <plate>
    <metadata key="index" value="1"/>
    <metadata key="prediction" value="3600"/>
    <metadata key="weight" value="25.0"/>
    <filament id="1" type="PLA" used_g="25.0" />
  </plate>
</config>`);
  zip.file('Metadata/project_settings.config', JSON.stringify({
    printer_settings_id: 'Bambu Lab X1 Carbon 0.4 nozzle',
    filament_type: ['PLA'],
  }));
  const buf = await zip.generateAsync({ type: 'arraybuffer' });
  const file = new File([buf], 'project.3mf', { type: 'application/octet-stream' });

  const input = screen.getByLabelText(/file input/i) as HTMLInputElement;
  await userEvent.upload(input, file);

  await waitFor(() => expect(onImport).toHaveBeenCalledTimes(1));
  expect(onImport.mock.calls[0][0].flavor).toBe('BambuStudio');
  expect(onImport.mock.calls[0][0].printerModel).toBe('Bambu Lab X1 Carbon');
});
