import { render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import FileDropZone from './FileDropZone';

const prusaSample = `; generated by PrusaSlicer 2.7.4
; printer_model = MK4
; filament_type = PLA
; filament used [g] = 47.2
; estimated printing time (normal mode) = 1h 23m 45s
`;

test('reads dropped file, parses, and calls onImport', async () => {
  const onImport = jest.fn();
  const onError = jest.fn();
  render(<FileDropZone onImport={onImport} onError={onError} />);

  const file = new File([prusaSample], 'sample.gcode', { type: 'text/plain' });
  const input = screen.getByLabelText(/g-code file input/i) as HTMLInputElement;
  await userEvent.upload(input, file);

  await waitFor(() => expect(onImport).toHaveBeenCalledTimes(1));
  expect(onImport.mock.calls[0][0].flavor).toBe('PrusaSlicer');
});

test('calls onError for unsupported file', async () => {
  const onImport = jest.fn();
  const onError = jest.fn();
  render(<FileDropZone onImport={onImport} onError={onError} />);

  const file = new File(['not a gcode'], 'sample.gcode', { type: 'text/plain' });
  const input = screen.getByLabelText(/g-code file input/i) as HTMLInputElement;
  await userEvent.upload(input, file);

  await waitFor(() => expect(onError).toHaveBeenCalledTimes(1));
  expect(onError.mock.calls[0][0].kind).toBe('unsupported_slicer');
});

test('shows imported summary when importedSource provided', () => {
  render(
    <FileDropZone
      onImport={() => {}}
      onError={() => {}}
      imported={{ source: 'PrusaSlicer', printer: 'MK4', filamentType: 'PLA', grams: 47.2, hoursLabel: '1h 23m' }}
      onClearImport={() => {}}
    />,
  );
  expect(screen.getByText(/PrusaSlicer/)).toBeInTheDocument();
  expect(screen.getByText(/MK4/)).toBeInTheDocument();
});
